import csv
import requests
import os
from dotenv import load_dotenv
from request_response_csv import request_response
from datetime import datetime, timezone, timedelta

load_dotenv()
username = input("Please enter your name: ").upper()
url = os.getenv("CHATBOT_URL")
api_key = os.getenv("API_KEY")

headers = {
    "X-API-KEY": api_key,
    "Content-Type": "application/json"
}

data = [
    ["Concept", "Input", "Expected Output"],
    ["Single trigger", "what is heart_score?", "The Heart Score is an accurate, statistically backed assessment of your own risk of heart disease and just how immediate that concern may be. It is a self-assessment that helps us gather general information about the state of your heart. The information that you learn from the Heart Score, will then take you down the learning journey that will enable you to understand what steps you can take to improve on those factors that are able to be changed with lifestyle intervention.The Heart Score assessment should take about 20 minutes to complete."],
    ["Single trigger, Multiple Intent", "what is heart_score? and why is it important", "The Heart Score is an accurate, statistically backed assessment of your own risk of heart disease and just how immediate that concern may be. It is a self-assessment that helps us gather general information about the state of your heart. The information that you learn from the Heart Score, will then take you down the learning journey that will enable you to understand what steps you can take to improve on those factors that are able to be changed with lifestyle intervention.The Heart Score assessment should take about 20 minutes to complete. The first Heart Score assessment helps provide us with a first benchmark or starting place. It also helps us adapt the MyAdesso experience to your needs. Over time we can begin to see whether both heart factors and your understanding of them continue to improve. "],
    ["Single Synonym", "what is private ?", "You will be asked to consent for us to look at your data at the start of MyAdesso. If you are in the MyAdesso clinical program, your responses will be shared with your healthcare provider. Otherwise, your responses to your heart score assessment are kept completely private and confidential. It is HIPAA compliant and multiple security tools are used to protect your information and data."],
    ["Single Synonym, Multiple Intent", "what is private? and why is it important", "You will be asked to consent for us to look at your data at the start of MyAdesso. If you are in the MyAdesso clinical program, your responses will be shared with your healthcare provider. Otherwise, your responses to your heart score assessment are kept completely private and confidential. It is HIPAA compliant and multiple security tools are used to protect your information and data. Each question of our Heart Score assessment corresponds to research related to heart risk. Understanding these factors allows us to get a complete picture of the factors that may contribute to the state and risks of your heart. "],
    ["Single Keyword", "How do I test cholesterol ", "Cholesterol levels are tested through a blood test called a lipid panel, which measures total cholesterol, LDL, HDL, and triglycerides. It's recommended to fast for 9-12 hours before the test for accurate results."],
    ["Single Keyword, Multiple Intent", "what is cholesterol? and how to prevent it", "Cholesterol is a waxy, fat-like substance found in all the cells of the body. While the body needs some cholesterol to make hormones, vitamin D, and substances that help digest food, having too much cholesterol in the blood can increase the risk of heart disease. Cholesterol levels are tested through a blood test called a lipid panel, which measures total cholesterol, LDL, HDL, and triglycerides. It's recommended to fast for 9-12 hours before the test for accurate results."],
    ["Multiple Synonyms","What is private and vaping ","You will be asked to consent for us to look at your data at the start of MyAdesso. If you are in the MyAdesso clinical program, your responses will be shared with your healthcare provider. Otherwise, your responses to your heart score assessment are kept completely private and confidential. It is HIPAA compliant and multiple security tools are used to protect your information and data. \n\n Vaping is not a safe alernative to smoking. Vaping is deeply unhealthy and introduces toxins into your body that we are just beginning to understand the heart effects of."],
    ["Multiple Synonyms, Multiple Intent","why is assessment important and how is systemic_lupus_erythematosus prevented?","The first Heart Score assessment helps provide us with a first benchmark or starting place. It also helps us adapt the MyAdesso experience to your needs. Over time we can begin to see whether both heart factors and your understanding of them continue to improve. We will ask you to re-take the Heart Score every six months and you will be able to review your heart score categories and how they have changed over time. \n\n Managing inflammation and traditional cardiovascular risk factors in people with autoimmune diseases to help reduce their heart disease risk. This can include creating a routine of movement, nourishing yourself through what you consume, reducing stress and building healthy relationships alongside medical treatments, prescriptions, and routines."],
    ["Multiple Keywords","How long is the heart score and Why doesn't MyAdesso list my gender","We will ask you to re-take the Heart Score every six months and you will be able to review your heart score categories and how they have changed over time. \n\n EWhile MyAdesso supports the right of each individual to gender-identify however they desire, understanding biological factors related to your gender at birth, allows us to better assess your risks. We have provided an ""other"" category for those who wish to abstain from identifying gender at birth or for those who were intersex at birth."],
    ["Multiple Keywords, Multiple Intent","How long is the heart score and Why doesn't MyAdesso list my gender","We will ask you to re-take the Heart Score every six months and you will be able to review your heart score categories and how they have changed over time. \n\n EWhile MyAdesso supports the right of each individual to gender-identify however they desire, understanding biological factors related to your gender at birth, allows us to better assess your risks. We have provided an ""other"" category for those who wish to abstain from identifying gender at birth or for those who were intersex at birth."],
    ["Combination of Trigger and Synonym with multiple intent","What is smoking and why is Lipoprotein(a) important","Smoking is one of the greatest risk factors for heart disease.  It is especially damaging to the lining of the arteries, the endothelium, which protects the arteries from developing plaque. On average, smokers die 10 years earlier than those who don't. The good news is, the minute you stop smoking is the minute you begin fixing yourself! Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks. \n\n Lipoprotein(a), or Lp(a), is tested for heart risk because elevated levels of Lp(a) are associated with an increased risk of cardiovascular diseases, including heart attack, stroke, and aortic valve stenosis. Unlike other forms of cholesterol, Lp(a) is largely determined by genetics and doesn't respond well to lifestyle changes, which makes it a unique and significant marker for assessing cardiovascular risk"],
    ["Combination of Trigger and Synonym without multiple intent","What is marital_status and race","Generally, heart research has shown that those who aren't partnered have as much as 42% increased risk of heart disease and that relational status and intimacy can positively influence heart health. This often goes back to the impact of lonliness, depression, and anxiety on the heart. A supportive relationship, like marriage, is associated with an improved cardiovascular status. \n\n Research shows that certain races and ethnicities are at higher heart risk due to either biological and/or cultural factors.For instance, 56% of Black women have high blood pressure and almost 46% of Hispanic women have diabetes or are prediabetic, both of which conditions have a major impact on heart health. At the same time, you are not a statistic ‚Äì you're a human being with your own choices. Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks."],
    ["Combination of Trigger and Keyword with multiple intent","what is smoking and How do I test cholesterol","Smoking is one of the greatest risk factors for heart disease.  It is especially damaging to the lining of the arteries, the endothelium, which protects the arteries from developing plaque. On average, smokers die 10 years earlier than those who don't. The good news is, the minute you stop smoking is the minute you begin fixing yourself! Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks. \n\n Cholesterol levels are tested through a blood test called a lipid panel, which measures total cholesterol, LDL, HDL, and triglycerides. It's recommended to fast for 9-12 hours before the test for accurate results."],
    ["Combination of Trigger and Keyword without multiple intent","what is age and What is Lp(a)","Heart risk increases with age, and especially as a women enters menopause. While younger women still can and do suffer from heart disease, the risk becomes more pronounced after age 55. \n\n Lipoprotein(a), or Lp(a), is a type of cholesterol that can increase the risk of heart disease and stroke. High levels of Lp(a) contribute to plaque buildup in arteries, making it a significant factor in heart risk.To test for Lp(a), a specific blood test is required."],
    ["Combination of Keyword and Synonym with multiple intent","How does marital status affect my heart health and what is insomnia","Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks.\n\n Poor sleep elevates the sympathetic nervous system, throws off circadian rhythms, triggers inflammation, and elevates insulin which raises your blood sugar. Chronically sleep-deprived people who regularly sleep less than 6 hours face a greater risk of hypertension, heart attack, arrhythmias, congestive heart failure, stroke, and death. We recommend getting 7-10 hours of sleep each night to keep your heart healthy. Your MyAdesso journey will help you improve your sleep habits as we provide you with the knowledge, tools, motivations and habits to live your healthiest life."],
    ["Combination of Keyword and Synonym without multiple intent","what is mood and food insecurity","When your nervous system is activated from stress, anxiety or depression, your heart beats faster, causing the arteries to become stiffer and the heart to work harder. This has longterm negative effects on the heart. When your emotions are calm and collected, your heart beats at a normal pace, with a variation of your heart beat as you breathe. This variation is called heart rate variability. Your MyAdesso journey will help you ground and refresh your heart as we provide you with the knowledge, tools, motivations and habits to live your healthiest life. \n\n Food insecurity means not having access to enough food, or enough healthy, quality food to meet one's basic needs.  Not having adequate or access to quality, healthy food can contribute to heart risk."],
    ["Combination of Trigger, Synonym and Keyword without intent","What is heart_score, private and food insecurity","The Heart Score is an accurate, statistically backed assessment of your own risk of heart disease and just how immediate that concern may be. It is a self-assessment that helps us gather general information about the state of your heart. The information that you learn from the Heart Score, will then take you down the learning journey that will enable you to understand what steps you can take to improve on those factors that are able to be changed with lifestyle intervention.The Heart Score assessment should take about 20 minutes to complete. \n\n You will be asked to consent for us to look at your data at the start of MyAdesso. If you are in the MyAdesso clinical program, your responses will be shared with your healthcare provider. Otherwise, your responses to your heart score assessment are kept completely private and confidential. It is HIPAA compliant and multiple security tools are used to protect your information and data. \n\n Food insecurity means not having access to enough food, or enough healthy, quality food to meet one's basic needs.  Not having adequate or access to quality, healthy food can contribute to heart risk."],
    ["Combination of Trigger, Synonym and Keyword with intent","What is cholesterol why is Lipoprotein(a) important and How does marital status affect my heart health","Cholesterol is a waxy, fat-like substance found in all the cells of the body. While the body needs some cholesterol to make hormones, vitamin D, and substances that help digest food, having too much cholesterol in the blood can increase the risk of heart disease.Cholesterol levels are tested through a blood test called a lipid panel, which measures total cholesterol, LDL, HDL, and triglycerides. It's recommended to fast for 9-12 hours before the test for accurate results. \n\n Lipoprotein(a), or Lp(a), is tested for heart risk because elevated levels of Lp(a) are associated with an increased risk of cardiovascular diseases, including heart attack, stroke, and aortic valve stenosis. Unlike other forms of cholesterol, Lp(a) is largely determined by genetics and doesn't respond well to lifestyle changes, which makes it a unique and significant marker for assessing cardiovascular risk \n\n Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks."],
    ["Only trigger word", "age", "Heart risk increases with age, and especially as a women enters menopause. While younger women still can and do suffer from heart disease, the risk becomes more pronounced after age 55. \n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
    ["Only trigger word - multiple", "age alcohol", "Heart risk increases with age, and especially as a women enters menopause. While younger women still can and do suffer from heart disease, the risk becomes more pronounced after age 55.  \n\n Moderation is really the key to drinking alcohol. People who reported more frequent alcohol intake showed 31.5% more stretching of the heart wall. The recommended maximum amount is one drink for women and two for men; this is moderation. And let’s be careful with what “a drink” means. For example, a pint of beer is 16 ounces. But a single drink of beer is 12 oz. So with one pint and you’re already at a drink and half. Likewise, a single drink of wine is 4  oz. A 1.5 oz. of 80-proof spirits or 1 oz. of 100-proof spirits is a single drink. And if moderation is not an option for you, abstinence may be necessary in order to curb the negative effects of drinking on your heart.\n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
    ["Only synonym word", "vaping", "Vaping is not a safe alernative to smoking. Vaping is deeply unhealthy and introduces toxins into your body that we are just beginning to understand the heart effects of.\n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
    ["Only synonym word - multiple", "vaping insomnia", "Vaping is not a safe alernative to smoking. Vaping is deeply unhealthy and introduces toxins into your body that we are just beginning to understand the heart effects of. \n\n Poor sleep elevates the sympathetic nervous system, throws off circadian rhythms, triggers inflammation, and elevates insulin which raises your blood sugar. Chronically sleep-deprived people who regularly sleep less than 6 hours face a greater risk of hypertension, heart attack, arrhythmias, congestive heart failure, stroke, and death. We recommend getting 7-10 hours of sleep each night to keep your heart healthy. Your MyAdesso journey will help you improve your sleep habits as we provide you with the knowledge, tools, motivations and habits to live your healthiest life.\n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
    ["Only keyword word", "What is Hemoglobin A1C", "The Hemoglobin A1C test measures your average blood sugar levels over the past 2-3 months. It’s used to diagnose and monitor diabetes, and higher A1C levels indicate a greater risk of heart disease."],
    ["Only keyword word - multiple", "How will the heart score be used  How does weight affect the heart","We will ask you to re-take the Heart Score every six months and you will be able to review your heart score categories and how they have changed over time. \n\n Weight Is associated with diabetes, high cholesterol, and high blood pressure, the major risk factors for heart disease. Losing weight can have a significant impact on our health. Even losing 5-10% of your body weight can reduce the risk of cardiovascular disease and high blood pressure. Reducing calories to 1200-1500 calories per day for women and 1500-1800 calories per day for men, might be enough to lose weight over time. Your MyAdesso journey will help you understand how to reach your weight goals, and decrease your overall risks as we provide you with the knowledge, tools, motivations and habits to live your healthiest life.\n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
    ["Domain relevance", "what is football", "I'm sorry, I can only answer questions related to women's heart health. Can you please clarify your question?"],
    ["Fallback", "what health", "This is a placeholder response generated for your question."],
    ["multiple triggers", "what is diet and what is sleep", "How you eat and nourish yourself has a significant impact on your heart health from increasing or decreasing cholesterol, to gaining or losing weight, to impacting your blood pressure. Various foods interact differently with your body and your heart. Your MyAdesso journey will help you improve how you nourish yourself and decrease your risk of heart disease, as we provide you with the knowledge, tools, motivations and habits to live your healthiest life. \n\n Poor sleep elevates the sympathetic nervous system, throws off circadian rhythms, triggers inflammation, and elevates insulin which raises your blood sugar. Chronically sleep-deprived people who regularly sleep less than 6 hours face a greater risk of hypertension, heart attack, arrhythmias, congestive heart failure, stroke, and death. We recommend getting 7-10 hours of sleep each night to keep your heart healthy. Your MyAdesso journey will help you improve your sleep habits as we provide you with the knowledge, tools, motivations and habits to live your healthiest life."],
    ["multiple triggers and multiple intent", "what is diet and how is marital_status important ", "Generally, heart research has shown that those who aren’t partnered have as much as 42% increased risk of heart disease and that relational status and intimacy can positively influence heart health. This often goes back to the impact of lonliness, depression, and anxiety on the heart. A supportive relationship, like marriage, is associated with an improved cardiovascular status.  Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks. \n\n How you eat and nourish yourself has a significant impact on your heart health from increasing or decreasing cholesterol, to gaining or losing weight, to impacting your blood pressure. Various foods interact differently with your body and your heart. Your MyAdesso journey will help you improve how you nourish yourself and decrease your risk of heart disease, as we provide you with the knowledge, tools, motivations and habits to live your healthiest life. How you eat and nourish yourself has a significant impact on your heart health from increasing or decreasing cholesterol, to gaining or losing weight, to impacting your blood pressure. Various foods interact differently with your body and your heart. Your MyAdesso journey will help you improve how you nourish yourself and decrease your risk of heart disease, as we provide you with the knowledge, tools, motivations and habits to live your healthiest life."],
    ["only intent", "how", "I'm sorry, I can only answer questions related to women's heart health. Can you please clarify your question?"],
    ["Spell check", "wat is smoking", "Smoking is one of the greatest risk factors for heart disease.  It is especially damaging to the lining of the arteries, the endothelium, which protects the arteries from developing plaque. On average, smokers die 10 years earlier than those who don’t. The good news is, the minute you stop smoking is the minute you begin fixing yourself! Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks."],
    ["Greetings", "hi", "I'm sorry, I can only answer questions related to women's heart health. Can you please clarify your question?"],
    ["Edge Case", "diet smoking?", "Smoking is one of the greatest risk factors for heart disease.  It is especially damaging to the lining of the arteries, the endothelium, which protects the arteries from developing plaque. On average, smokers die 10 years earlier than those who don’t. The good news is, the minute you stop smoking is the minute you begin fixing yourself! Your MyAdesso journey will help you understand your risks and provide you with the knowledge, tools, motivations and habits to live your healthiest life and overcome these risks. \n\n How you eat and nourish yourself has a significant impact on your heart health from increasing or decreasing cholesterol, to gaining or losing weight, to impacting your blood pressure. Various foods interact differently with your body and your heart. Your MyAdesso journey will help you improve how you nourish yourself and decrease your risk of heart disease, as we provide you with the knowledge, tools, motivations and habits to live your healthiest life.\n For personalized advice or concerns about your health, Please consult our healthcare professional. We can provide you with the best guidance based on your specific needs."],
]

script_dir = os.path.dirname(os.path.abspath(__file__))
csv_file = os.path.join(script_dir, "test.csv")

def create_csv(csv_file):
    with open(csv_file, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerows(data)

def get_bot_response(user_input):
    try:
        payload = {"user-input": user_input}
        response = requests.post(url, headers=headers, json=payload)
        return response.json().get("data", {}).get("chatbot-response")
    except requests.RequestException as e:
        print(f"Request failed: {e}")
        return ""

def test_chatbot_responses(csv_file):
    pass_count = 0
    fail_count = 0

    with open(csv_file, mode='r', newline='', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        rows = list(reader)

    for row in rows:
        user_input = row["Input"]
        expected_output = row["Expected Output"]
        bot_response = get_bot_response(user_input)

        print(f"Testing input: {user_input}")
        print(f"Expected Output: {expected_output}")

        if isinstance(bot_response, list):
            bot_response_str = ' '.join([str(item) for item in bot_response])
        else:
            bot_response_str = bot_response

        print(f"Bot Response: {bot_response_str}")

        result = "PASS" if bot_response_str.strip() == expected_output.strip() else "FAIL"
        print("Test Passed: ", result)
        print("-" * 50)

        row["Result"] = result
        if result == "PASS":
            pass_count += 1
        else:
            fail_count += 1

    with open(csv_file, mode='w', newline='', encoding='utf-8') as file:
        fieldnames = ["Concept", "Input", "Expected Output", "Result"]
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    current_time = datetime.now(timezone(timedelta(hours=9))).strftime("%Y-%m-%d %H:%M:%S")
    print(f"\nSummary:")
    print(f"Test Conducted By: {username}")
    print(f"Time of execution: {current_time}")
    print(f"Total PASS cases: {pass_count}")
    print(f"Total FAIL cases: {fail_count}")
    if fail_count == 0:
        print(f"__________________________________")
        print(f"GOOD JOB {username}🥳🥳🥳!!! All test cases are cleared")
    else:
        print(f"__________________________________")
        print(f"Sorry {username}😞😞😞, Please check the code once again. \n There are {fail_count} Cases failed.")

create_csv(csv_file)
test_chatbot_responses(csv_file)